language: php

cache:
  directories:
    - $HOME/.composer/cache

services:
  - memcached

env:
  global:
    - COMPOSER_ARGS="--no-interaction"
    - COVERAGE_DEPS="php-coveralls/php-coveralls"
    - SERIALIZER_DEPS="laminas/laminas-serializer"

matrix:
  fast_finish: true
  include:
    - php: 5.6
      env:
        - DEPS=lowest
        - MEMCACHE_PECL_VERSION="memcache-3.0.8"
    - php: 5.6
      env:
        - DEPS=latest
        - MEMCACHE_PECL_VERSION="memcache-3.0.8"
    - php: 7.0
      env:
        - DEPS=lowest
        - MEMCACHE_PECL_VERSION="memcache-4.0.5.2"
    - php: 7.0
      env:
        - DEPS=latest
        - MEMCACHE_PECL_VERSION="memcache-4.0.5.2"
    - php: 7.1
      env:
        - DEPS=lowest
        - MEMCACHE_PECL_VERSION="memcache-4.0.5.2"
    - php: 7.1
      env:
        - DEPS=latest
        - MEMCACHE_PECL_VERSION="memcache-4.0.5.2"
    - php: 7.2
      env:
        - DEPS=lowest
        - MEMCACHE_PECL_VERSION="memcache-4.0.5.2"
    - php: 7.2
      env:
        - DEPS=latest
        - MEMCACHE_PECL_VERSION="memcache-4.0.5.2"
    - php: 7.3
      env:
        - DEPS=lowest
        - MEMCACHE_PECL_VERSION="memcache-4.0.5.2"
    - php: 7.3
      env:
        - DEPS=latest
        - MEMCACHE_PECL_VERSION="memcache-4.0.5.2"
    - php: 7.4
      env:
        - DEPS=lowest
        - MEMCACHE_PECL_VERSION="memcache-4.0.5.2"
    - php: 7.4
      env:
        - DEPS=latest
        - CS_CHECK=true
        - TEST_COVERAGE=true
        - MEMCACHE_PECL_VERSION="memcache-4.0.5.2"

before_install:
  - if [[ $TEST_COVERAGE != 'true' ]]; then phpenv config-rm xdebug.ini || return 0 ; fi

install:
  - yes|CFLAGS="-fgnu89-inline" pecl install -f $MEMCACHE_PECL_VERSION
  - travis_retry composer install $COMPOSER_ARGS
  - travis_retry composer require --dev $COMPOSER_ARGS $SERIALIZER_DEPS
  - if [[ $DEPS == 'latest' ]]; then travis_retry composer update $COMPOSER_ARGS ; fi
  - if [[ $DEPS == 'lowest' ]]; then travis_retry composer update --prefer-lowest --prefer-stable $COMPOSER_ARGS ; fi
  - if [[ $TEST_COVERAGE == 'true' ]]; then travis_retry composer require --dev $COMPOSER_ARGS $COVERAGE_DEPS ; fi
  - stty cols 120 && composer show

script:
  - if [[ $TEST_COVERAGE == 'true' ]]; then composer run-script test-coverage -- --verbose ; else composer run-script test -- --verbose ; fi
  - if [[ $CS_CHECK == 'true' ]]; then composer cs-check ; fi

after_script:
  - if [[ $TEST_COVERAGE == 'true' ]]; then travis_retry vendor/bin/php-coveralls -v ; fi

notifications:
  email: false
